# PRAKTIKUM 4
__Solusi Sistem Persamaan Linear : Metode Iteratif__

### 6.6.2 Soal Pemrograman

```Nama : Antonius Aditya Rizky Wijaya```

```NIM : G5402221003```

<hr style="border:2px solid black"> </hr>

 ## Metode Jacobi

In [42]:
using LinearAlgebra
function jacobi(A, B, Xawal::Array{Int64,1})
    # Definisikan nilai toleransi dan maksimum iterasi yang ditentukan.
    delta = 10^-7;
    maxi = 100;
    flag = 1;
    # Dekomposisi matriks A menjadi A=D+R
    D = Diagonal(diag(A))
    R = A - D;
    # Tentukan nilai tebakan awal dari metode Jacobi
    X = Xawal;
    M = [0 X' NaN];
    # Mulai proses iterasi metode jacobi
    for k = 1:maxi
        Xlama = X;
        X = inv(D)*(B - R*Xlama); # Isi dengan rumus iterasi jacobi
        # Hitung panjang vektor galat iterasi jacobi, jika Xn-Xn-1 atau B-AX telah memenuhi toleransi maka proses iterasi dapat dihentikan.
        err = norm(X-Xlama);
        M = [M; [k X' err] ];
        if err<delta || norm(B-A*X)<delta
            flag = 0;
            break
        end
    end
    err = M[end,end]
    return X, flag, err, M
end

jacobi (generic function with 1 method)

In [43]:
A = [4 -1  1
     4 -8  1
    -2  1  5];
B = [7;-21;15];
Xa = [1,2,2];
X,flag,err,M = jacobi(A,B,Xa)
@show X
@show flag
@show err
M

X = [1.9999999884128572, 3.9999999907302857, 3.0000000018539428]
flag = 0
err = 3.777053140308286e-8


18×5 Matrix{Float64}:
  0.0  1.0      2.0      2.0      NaN
  1.0  1.75     3.375    3.0        1.85826
  2.0  1.84375  3.875    3.025      0.509327
  3.0  1.9625   3.925    2.9625     0.143205
  4.0  1.99062  3.97656  3.0        0.0696847
  5.0  1.99414  3.99531  3.00094    0.0190998
  6.0  1.99859  3.99719  2.99859    0.00537021
  7.0  1.99965  3.99912  3.0        0.00261318
  8.0  1.99978  3.99982  3.00004    0.000716241
  9.0  1.99995  3.99989  2.99995    0.000201383
 10.0  1.99999  3.99997  3.0        9.79941e-5
 11.0  1.99999  3.99999  3.0        2.6859e-5
 12.0  2.0      4.0      3.0        7.55185e-6
 13.0  2.0      4.0      3.0        3.67478e-6
 14.0  2.0      4.0      3.0        1.00721e-6
 15.0  2.0      4.0      3.0        2.83194e-7
 16.0  2.0      4.0      3.0        1.37804e-7
 17.0  2.0      4.0      3.0        3.77705e-8

In [ ]:
using Pkg
Pkg.add("Plots")

In [ ]:
using Plots
# Plot panjang vektor galat.
iter = M[:,1]
err = M[:,end]
p1 = plot(iter, err, yaxis = :log, label = :none)
# Tambahkan title dan label
title!("Plot perambatan panjang vektor galat")
xlabel!("iterasi")
ylabel!("panjang vektor galat")

## Metode Gauss-Seidel

In [44]:
using LinearAlgebra
function gaussSeidel(A,B,Xawal::Array{Int64,1}) 
    # Definisikan nilai toleransi dan maksimum iterasi yang ditentukan.
    delta = 10^-7;
    maxi = 100;
    flag = 1;
    # Dekomposisi matriks A menjadi A=L+U
    D = Diagonal(diag(A))
    R = tril(A);
    U = triu(A,1);
    # Tentukan nilai tebakan awal dari metode Gauss-Seidel
    X = Xawal; 
    M = [0 X' NaN];
    # Mulai proses iterasi metode Gauss-Seidel
    for k = 1:maxi
        Xlama = X;
        X = inv(R)*(B - U*Xlama); # Isi dengan rumus iterasi Gauss-Seidel 
        # Hitung panjang vektor galat iterasi jacobi, jika galat telah 
        # memenuhi toleransi maka proses iterasi dapat dihentikan.
        err = norm(X-Xlama);
        M = [M; [k X' err] ];
        if err<delta
            flag = 0;
            break
        end
    end
    err = M[end,end]
    return X, flag, err, M
end

gaussSeidel (generic function with 1 method)

In [45]:
A = [4 -1  1
     4 -8  1
    -2  1  5];
B = [7;-21;15];
Xa = [1,2,2];
X,flag,err,M = gaussSeidel(A,B,Xa)
@show X
@show flag
@show err
M

X = [1.99999999743314, 3.999999998137355, 2.999999999345785]
flag = 0
err = 2.1378379298357413e-8


11×5 Matrix{Float64}:
  0.0  1.0      2.0      2.0      NaN
  1.0  1.75     3.75     2.95       2.12779
  2.0  1.95     3.96875  2.98625    0.298606
  3.0  1.99562  3.99609  2.99903    0.0547054
  4.0  1.99927  3.99951  2.9998     0.00505308
  5.0  1.99993  3.99994  2.99998    0.000807443
  6.0  1.99999  3.99999  3.0        8.30727e-5
  7.0  2.0      4.0      3.0        1.21519e-5
  8.0  2.0      4.0      3.0        1.34052e-6
  9.0  2.0      4.0      3.0        1.85294e-7
 10.0  2.0      4.0      3.0        2.13784e-8

In [ ]:
# Plot panjang vektor galat.
iter = M[:,1]
err = M[:,end]
p2= plot(iter, err, yaxis = :log, label = :none)
# Tambahkan title dan label
title!("Plot perambatan panjang vektor galat")
xlabel!("iterasi")
ylabel!("panjang vektor galat")

## Metode Rekonstruksi Aljabar

In [46]:
using LinearAlgebra
function rekons(A,B,Xawal::Array{Int64,1})
    delta = 10^-7;
    maxi = 100;
    flag = 1; 
    X = Xawal;
    Xlama = X;
    M = [0 X' NaN]; 
    for k = 1:maxi
        for i = 1:length(B)
            Xlama = X; 
            X = Xlama + A[i,:]*(B[i]-A[i,:]'Xlama)/(A[i,:]'A[i,:])
        end
        err = norm(X-Xlama) 
        M = [M; [k X' err] ];
        if err<delta
            flag = 0;
            break
        end
    end
    err = M[end,end]
    return X, flag, err, M
end

rekons (generic function with 1 method)

In [47]:
A = [4 -1  1
     4 -8  1
    -2  1  5];
B = [7;-21;15];
Xa = [1,2,2];
X,flag,err,M = rekons(A,B,Xa)
@show X
@show flag
@show err
M

X = [1.9999987931831584, 3.9999993707528194, 2.9999996431226994]
flag = 0
err = 7.477270454885512e-8


18×5 Matrix{Float64}:
  0.0  1.0       2.0      2.0      NaN
  1.0  0.677229  3.45151  2.58059    0.658544
  2.0  1.51207   3.75397  2.85403    0.0644652
  3.0  1.79762   3.89498  2.94005    0.0145717
  4.0  1.91453   3.95547  2.97472    0.0054161
  5.0  1.96381   3.98113  2.9893     0.00224922
  6.0  1.98467   3.99201  2.99547    0.000950041
  7.0  1.99351   3.99662  2.99808    0.000402252
  8.0  1.99725   3.99857  2.99919    0.000170373
  9.0  1.99884   3.99939  2.99966    7.21649e-5
 10.0  1.99951   3.99974  2.99985    3.0567e-5
 11.0  1.99979   3.99989  2.99994    1.29473e-5
 12.0  1.99991   3.99995  2.99997    5.48412e-6
 13.0  1.99996   3.99998  2.99999    2.32292e-6
 14.0  1.99998   3.99999  3.0        9.83924e-7
 15.0  1.99999   4.0      3.0        4.16762e-7
 16.0  2.0       4.0      3.0        1.76529e-7
 17.0  2.0       4.0      3.0        7.47727e-8

In [ ]:
# Plot panjang vektor galat.
iter = M[:,1]
err = M[:,end]
p3 = plot(iter, err, yaxis = :log, label = :none)
# Tambahkan title dan label
title!("Plot perambatan panjang vektor galat")
xlabel!("iterasi")
ylabel!("panjang vektor galat")

## Conjugate Gradient

In [48]:
using LinearAlgebra
function conGrad(A,B,Xawal::Array{Int64,1})
    if ~(isposdef(A) && issymmetric(A))
        error("matriks A harus simetrik definit positif")
    end
    delta = 10^-7;
    maxi = 10000;
    flag = 1; 
    X = Xawal;
    r = B-A*X
    d = r
    M = [0 X' NaN]; 
    for k = 1:maxi
        Xlama = X
        rlama = r
        dlama = d
        X = Xlama + ((rlama'rlama)/(dlama'A*dlama))*dlama
        r = rlama - ((rlama'rlama)/(dlama'A*dlama))*A*dlama
        d = r - ((r'r)/(rlama'rlama))*dlama
        err = norm(X-Xlama) 
        M = [M; [k X' err] ];
        if err<delta
            flag = 0;
            break
        end
    end
    err = M[end,end]
    return X, flag, err, M
end

conGrad (generic function with 1 method)

In [49]:
A = [4 -1  1
     4 -8  1
    -2  1  5];
B = [7;-21;15];
Xa = [1,2,2];
X,flag,err,M = conGrad(A,B,Xa)

LoadError: matriks A harus simetrik definit positif

In [50]:
Amod = A'A
Bmod = A'B
Xa = [1,2,2];
X,flag,err,M = conGrad(Amod,Bmod,Xa)
@show X
@show flag
@show err
M

X = [1.9999966511060345, 3.999996358616926, 2.9999993316545996]
flag = 0
err = 9.99868997820265e-8


7907×5 Matrix{Float64}:
    0.0  1.0       2.0      2.0      NaN
    1.0  0.51751   3.03391  2.19529    1.15754
    2.0  1.05617   3.03635  2.64322    0.700569
    3.0  0.910543  3.16552  2.55507    0.213692
    4.0  1.33662   3.26162  2.87937    0.544011
    5.0  1.1788    3.314    2.76781    0.200238
    6.0  1.65265   3.53914  3.09575    0.618683
    7.0  1.47083   3.546    2.96153    0.226108
    8.0  1.92683   3.88324  3.18542    0.609751
    9.0  1.80419   3.87796  3.06276    0.173539
   10.0  1.92976   3.90414  3.04776    0.129151
   11.0  1.89275   3.91689  3.04243    0.0395145
   12.0  1.96006   3.93412  3.01269    0.0755878
    ⋮                                
 7895.0  2.0       4.0      3.0        1.0266e-7
 7896.0  2.0       4.0      3.0        1.00173e-7
 7897.0  2.0       4.0      3.0        1.02622e-7
 7898.0  2.0       4.0      3.0        1.00136e-7
 7899.0  2.0       4.0      3.0        1.02584e-7
 7900.0  2.0       4.0      3.0        1.00099e-7
 7901.0  2.0       4.

In [ ]:
# Plot panjang vektor galat.
iter = M[:,1]
err = M[:,end]
p4 = plot(iter, err, yaxis = :log, label = :none)
# Tambahkan title dan label
title!("Plot perambatan panjang vektor galat")
xlabel!("iterasi")
ylabel!("panjang vektor galat")

<hr style="border:2px solid black"> </hr>

### Soal 1

Dengan menggunakan metode __Jacobi__ dan __Gauss-Seidel__, carilah solusi SPL dibawah ini ! Apakah kedua metode konvergen ke solusi ? Jelaskan !

(a) Matriks 1

$$\begin{align*}
\begin{pmatrix}
  4 &  8 & 4 &  0 \\
 1 & 5 & 4 &  -3 \\
  1 & 4 &  7 & 2 \\
  1 & 3 & 0 &  -2 \\
\end{pmatrix}
\begin{pmatrix}
x_1\\x_2\\x_3\\x_4\\
\end{pmatrix}=
\begin{pmatrix}
6\\7\\14\\2
\end{pmatrix}
\end{align*}$$

(b) Matriks 2

$$\begin{align*}
\begin{pmatrix}
  8 &  1 & 4 &  0 \\
 1 & -9 & 1 &  -2 \\
  1 & 1 &  7 & 2 \\
  1 & 3 & 0 &  -5 \\
\end{pmatrix}
\begin{pmatrix}
x_1\\x_2\\x_3\\x_4\\
\end{pmatrix}=
\begin{pmatrix}
13\\-9\\11\\-1
\end{pmatrix}
\end{align*}$$


__(a) Matriks 1__

In [ ]:
# Metode Jacobi

A = [4 8 4 0
    1 5 4 -3
    1 4 7 2
    1 3 0 -2];
B = [6;7;14;2];
Xa = [1,2,3,4];
X,flag,err,M = jacobi(A,B,Xa)
@show X
@show flag
@show err
M

In [ ]:
# Metode Gauss-Seidel

A = [4 8 4 0
    1 5 4 -3
    1 4 7 2
    1 3 0 -2];
B = [6;7;14;2];
Xa = [1,2,3,4];
X,flag,err,M = gaussSeidel(A,B,Xa)
@show X
@show flag
@show err
M

__Penjelasan :__

Setelah 100 iterasi, solusi dari matriks 1 baik menggunakan metode Jacobi maupun Gauss-Seidel menghasilkan error yang besar (>1) dan flag = 1. Artinya dengan kedua metode tersebut, matriks 1 __tidak menghasilkan nilai yang konvergen ke solusi__.

__(b) Matriks 2__

In [ ]:
# Metode Jacobi

A = [8 1 4 0
    1 -9 1 -2
    1 1 7 2
    1 3 0 -5];
B = [13;-9;11;-1];
Xa = [1,2,3,4];
X,flag,err,M = jacobi(A,B,Xa)
@show X
@show flag
@show err
M

In [ ]:
# Metode Gauss-Seidel

A = [8 1 4 0
    1 -9 1 -2
    1 1 7 2
    1 3 0 -5];
B = [13;-9;11;-1];
Xa = [1,2,3,4];
X,flag,err,M = gaussSeidel(A,B,Xa)
@show X
@show flag
@show err
M

__Penjelasan :__

Setelah beberapa iterasi, solusi dari matriks 2 baik menggunakan metode Jacobi maupun Gauss-Seidel menghasilkan error yang kecil (<1) dan flag = 0. Artinya dengan kedua metode tersebut, matriks 2 __menghasilkan nilai yang konvergen ke solusi__.

<hr style="border:2px solid black"> </hr>

### Soal 3

Diberikan suatu sistem persamaan linear (SPL) sebagai berikut:

$$\begin{align*}
\begin{bmatrix}
  12 &  -2 & 1 &  0 & 0 & 0 & 0 &  0\\
  -2 & 12 & -2 &  1 & 0 & 0 & 0 &  0\\
  1 & -2 &  12 & -2 & 1 & 0 & 0 &  0\\
  0 & 1 & -2 &  12 & -2 & 1 & 0 &  0\\
  0 & 0 & 1 &  -2 & 12 & -2 & 1 &  0\\
  0 & 0 & 0 &  1 & -2 & 12 & -2 &  1\\
  0 & 0 & 0 &  0 & 1 & -2 & 12 &  -2\\
  0 & 0 & 0 &  0 & 0 & 1 & -2 &  12\\
\end{bmatrix}
\begin{bmatrix}
x_1\\x_2\\x_3\\x_4\\x_5\\x_6\\x_7\\x_8\\
\end{bmatrix}=
\begin{bmatrix}
5\\5\\5\\5\\5\\5\\5\\5\\
\end{bmatrix}
\end{align*}$$

(a) Gunakan metode iterasi Jacobi dan Gauss-Seidel untuk mencari solusi SPL diatas, lalu gambarkan plot perambatan galat masing-masing metode.

(b) Gunakan metode iterasi rekonstruksi aljabar dan conjugate gradient untuk mencari solusi SPL di atas, lalu gambarkan plot perambatan galat masing-masing metode.

(c) Apa yang terjadi terhadap nilai solusi jika dimensi SPL $AX = B$ diubah menjadi $A_{10×10}$, $A_{25×25}$, dan $A_{50×50}$.

In [55]:
# Metode iterasi Jacobi

A = diagm(0=>12*ones(8), 1=>-2*ones(7), -1=>-2*ones(7), 2=>ones(6), -2=>ones(6));
B = 5*ones(8);
Xa = [1,2,3,4,5,6,7,8];
X,flag,err,M = jacobi(A,B,Xa)
@show X
@show flag
@show err
M

X = [0.46381148766096825, 0.5373729743333224, 0.5090081763275643, 0.4971635075418928, 0.49716352943019065, 0.5090081568074184, 0.5373729891485015, 0.4638114784779091]
flag = 0
err = 7.82113169454377e-8


22×10 Matrix{Float64}:
  0.0  1.0       2.0       3.0       …  7.0       8.0       NaN
  1.0  0.5       0.75      0.916667     2.33333   1.08333    10.9246
  2.0  0.465278  0.5625    0.576389     0.729167  0.6875      1.98278
  3.0  0.462384  0.540509  0.524306     0.623264  0.46875     0.411263
  4.0  0.463059  0.540268  0.504389     0.536748  0.476804    0.106771
  5.0  0.464679  0.535715  0.511658  …  0.543897  0.461818    0.0367766
  6.0  0.463314  0.538298  0.507504     0.536044  0.465158    0.0149741
  7.0  0.464091  0.53689   0.509666     0.538185  0.463378    0.00647358
  8.0  0.463676  0.537601  0.50868      0.537086  0.464014    0.00285357
  9.0  0.463877  0.537264  0.509154     0.537508  0.46373     0.00126659
 10.0  0.463781  0.537423  0.50894   …  0.537317  0.463848    0.000563737
 11.0  0.463825  0.53735   0.509038     0.537398  0.463796    0.000251203
 12.0  0.463805  0.537383  0.508994     0.537362  0.463818    0.000111995
 13.0  0.463814  0.537368  0.509014     0.53737

In [57]:
# Metode iterasi Gauss-Seidel

A = diagm(0=>12*ones(8), 1=>-2*ones(7), -1=>-2*ones(7), 2=>ones(6), -2=>ones(6));
B = 5*ones(8);
Xa = [1,2,3,4,5,6,7,8];
X,flag,err,M = gaussSeidel(A,B,Xa)
@show X
@show flag
@show err
M

X = [0.4638114862743379, 0.5373729807886587, 0.5090081648366768, 0.4971635183265054, 0.49716351885805415, 0.5090081666857685, 0.5373729817041171, 0.4638114830602054]
flag = 0
err = 4.17066489746935e-8


12×10 Matrix{Float64}:
  0.0  1.0       2.0       3.0       …  7.0       8.0       NaN
  1.0  0.5       0.666667  0.736111     1.84097   0.640168   11.8241
  2.0  0.466435  0.548997  0.529803     0.601417  0.45814     1.40959
  3.0  0.464016  0.538365  0.516132     0.537242  0.4624      0.203213
  4.0  0.463383  0.540086  0.504338     0.536942  0.463695    0.0351857
  5.0  0.464653  0.536607  0.50878   …  0.537322  0.463809    0.00671948
  6.0  0.463703  0.537271  0.509073     0.53737   0.463812    0.00131516
  7.0  0.463789  0.537375  0.509021     0.537373  0.463812    0.00015758
  8.0  0.463811  0.537375  0.509009     0.537373  0.463811    2.5037e-5
  9.0  0.463812  0.537373  0.509008     0.537373  0.463811    2.19251e-6
 10.0  0.463812  0.537373  0.509008  …  0.537373  0.463811    2.93984e-7
 11.0  0.463811  0.537373  0.509008     0.537373  0.463811    4.17066e-8

In [58]:
# Metode iterasi rekonstruksi aljabar

A = diagm(0=>12*ones(8), 1=>-2*ones(7), -1=>-2*ones(7), 2=>ones(6), -2=>ones(6));
B = 5*ones(8);
Xa = [1,2,3,4,5,6,7,8];
X,flag,err,M = rekons(A,B,Xa)
@show X
@show flag
@show err
M

X = [0.463812279477824, 0.5373730726300844, 0.5090076655768303, 0.4971632866310348, 0.49716362141348247, 0.5090082631365513, 0.5373729864302567, 0.46381147581033016]
flag = 0
err = 4.715929787094704e-9


15×10 Matrix{Float64}:
  0.0  1.0       2.0       3.0       …  7.0       8.0       NaN
  1.0  0.546612  0.858156  1.06556      3.33535   0.844645    7.76375
  2.0  0.477731  0.612291  0.61189      0.938039  0.463404    0.759785
  3.0  0.475395  0.522859  0.62204      0.57245   0.452337    0.0401792
  4.0  0.436624  0.590135  0.470478     0.532768  0.459874    0.0137141
  5.0  0.483611  0.536735  0.489182  …  0.533848  0.46291     0.00677323
  6.0  0.46846   0.530539  0.505536     0.53621   0.463677    0.00190859
  7.0  0.462823  0.534629  0.509567     0.537103  0.463813    0.000380456
  8.0  0.462892  0.536839  0.509646     0.537334  0.463822    3.78875e-5
  9.0  0.463498  0.537391  0.509273     0.537375  0.463816    1.01956e-5
 10.0  0.463753  0.537432  0.509082  …  0.537377  0.463813    7.52612e-6
 11.0  0.463812  0.5374    0.509021     0.537375  0.463812    2.71863e-6
 12.0  0.463817  0.537381  0.509008     0.537373  0.463812    6.84223e-7
 13.0  0.463814  0.537375  0.509007     0.5

In [60]:
# Metode iterasi conjugate gradient

A = diagm(0=>12*ones(8), 1=>-2*ones(7), -1=>-2*ones(7), 2=>ones(6), -2=>ones(6));
B = 5*ones(8);
Xa = [1,2,3,4,5,6,7,8];
X,flag,err,M = rekons(A,B,Xa)
@show X
@show flag
@show err
M

X = [0.463812279477824, 0.5373730726300844, 0.5090076655768303, 0.4971632866310348, 0.49716362141348247, 0.5090082631365513, 0.5373729864302567, 0.46381147581033016]
flag = 0
err = 4.715929787094704e-9


15×10 Matrix{Float64}:
  0.0  1.0       2.0       3.0       …  7.0       8.0       NaN
  1.0  0.546612  0.858156  1.06556      3.33535   0.844645    7.76375
  2.0  0.477731  0.612291  0.61189      0.938039  0.463404    0.759785
  3.0  0.475395  0.522859  0.62204      0.57245   0.452337    0.0401792
  4.0  0.436624  0.590135  0.470478     0.532768  0.459874    0.0137141
  5.0  0.483611  0.536735  0.489182  …  0.533848  0.46291     0.00677323
  6.0  0.46846   0.530539  0.505536     0.53621   0.463677    0.00190859
  7.0  0.462823  0.534629  0.509567     0.537103  0.463813    0.000380456
  8.0  0.462892  0.536839  0.509646     0.537334  0.463822    3.78875e-5
  9.0  0.463498  0.537391  0.509273     0.537375  0.463816    1.01956e-5
 10.0  0.463753  0.537432  0.509082  …  0.537377  0.463813    7.52612e-6
 11.0  0.463812  0.5374    0.509021     0.537375  0.463812    2.71863e-6
 12.0  0.463817  0.537381  0.509008     0.537373  0.463812    6.84223e-7
 13.0  0.463814  0.537375  0.509007     0.5

In [51]:
using Pkg
Pkg.add("Plots")

    Updating registry at `C:\Users\MAT473\.julia\registries\General`


LoadError: GitError(Code:EOWNER, Class:Config, repository path 'C:/Users/MAT473/.julia/registries/General/' is not owned by current user)

In [61]:
using Plots
# Plot panjang vektor galat.
iter = M[:,1]
err = M[:,end]
p1 = plot(iter, err, yaxis = :log, label = :none)
# Tambahkan title dan label
title!("Plot perambatan panjang vektor galat")
xlabel!("iterasi")
ylabel!("panjang vektor galat")

LoadError: ArgumentError: Package Plots not found in current path.
- Run `import Pkg; Pkg.add("Plots")` to install the Plots package.